apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-first-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: my-first-disk
    fsType: ext4
