apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-storage
          mountPath: /data/redis
      volumes:
      - name: nginx-storage
        source:
          persistentVolumeClaim:
           accessMode: ReadWriteOnce
           claimRef:
             name: task-pv-claim
