FROM gradle:7.6.0-jdk8 as build-stage
WORKDIR /home/gradle/src
COPY --chown=gradle:gradle . .
RUN gradle build

FROM openjdk:8-jdk-alpine
COPY --from=build-stage /home/gradle/src/build/libs/spring-boot-docker-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
