apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-gcp-volume
spec:
  containers:
  - name: nginx-pod-gcp-volume
    image: nginx
    ports:
      - name: nginx-port
        containerPort: 80
    volumeMounts:
      - name: gcp-volume
        mountPath: /tmp
  volumes:
  - name: gcp-volume
    persistentVolumeClaim:
      claimName: my-readonly-pvc
